### ISSUE TITLE
Define new actions

### ISSUE THREAD

**Issue by jankrepl** [jankrepl/pychubby#14]
Defining new actions is very easy via the action `Lambda`. See detailed explanation here: [Custom actions](https://pychubby.readthedocs.io/en/latest/source/adding_custom_actions.html)

Some ideas 
- [ ] Scare
- [ ] Angrify
- [ ] Bore
- [ ] Projective Transform
- [ ] ...

**Comment by aplinxy9plin** [comment]
Can u help me? I want to save picture from plot. Can I do it?

**Comment by jankrepl** [comment]
> Can u help me? I want to save picture from plot. Can I do it?

Sure, the image is stored under the `img` attribute of the `LandmarkFace`.

So something like this should save the image

`plt.imsave('output_image.png', lf.img)`

**Comment by aplinxy9plin** [comment]
Can I get base64 image from this action? It'll be amazing.

**Comment by sandhyalaxmiK** [comment]
Example program how i saved open eyes of different scales in the following code:

![openeyes](https://user-images.githubusercontent.com/45446006/69329238-b88acd80-0c76-11ea-96af-a0c08eb25b16.png)

Open the above link and check @aplinxy9plin

**Comment by aplinxy9plin** [comment]
@sandhyalaxmiK, thank you, man! I'll use this code.
