### ISSUE TITLE
"shape_predictor_68_face_landmarks.dat" looks like under non-commercial license.

### ISSUE THREAD

**Issue by msuchoi** [jankrepl/pychubby#16]
First of all, thank you for your amazing work.

The thing is, "shape_predictor_68_face_landmarks.dat" looks like under non-commercial license.

I guess we cannot use this work for commercial purposes, right?

**Comment by jankrepl** [comment]
> First of all, thank you for your amazing work.

Thank you for using `pychubby`!

> The thing is, "shape_predictor_68_face_landmarks.dat" looks like under non-commercial license.
> I guess we cannot use this work for commercial purposes, right?

Personally, I am no legal expert. I just wanted to stay on the safe side in `pychubby` by explicitly stating that it relies on an external pretrained model. Please create an issue in the original repository https://github.com/davisking/dlib-models or even contact the author.

**Comment by msuchoi** [comment]
This pre-trained model can be an alternative one for commercial usage:
https://github.com/1adrianb/face-alignment
