### ISSUE TITLE
Set python_requires in setup.py

### ISSUE THREAD

**Issue by jankrepl** [jankrepl/pychubby#6]
So that it is not even possible to install on unsupported versions of Python

**Comment by fgriberi** [comment]
Hi guys, @jankrepl can I take this issue? My idea is adding a requirements folder with different files according each environment, for example, *dev.txt* and *test.txt*. Any suggestion is welcome

**Comment by jankrepl** [comment]
Hey, thanks for your interest!!


My idea was to add the `python_requires` entry to the`setup` function of `setup.py`.

See [link](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) for details.

Currently the tests are run for python 3.5, 3.6 and 3.7 so I suggest something like `python_requires='>=3.5'`.

The goal is to make sure that people with lower version of Python get an error right away after trying to `pip install pychubby`.

**Comment by fgriberi** [comment]
got it! I thought it was related to installation requirements. I'll take it :-)
